# Make management users and remove default creds from cumulus
- name: Allow 'adm' to passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%adm'
    line: '%adm ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create users
  user:
    name: "{{ item.username }}"
    groups:
      - adm
      - netedit
  with_items: "{{ admin_users }}"

- name: set ssh_dirs
  file:
    state: directory
    name: /home/{{item.username}}/.ssh
    owner: "{{item.username}}"
    group: adm
    mode: 0700
  with_items: "{{ admin_users }}"

- name: set public keys
  copy:
    content: {{ key_format | default ('ssh-rsa') }} {{ item.public_key }} {{ item.username }}
    dest: /home/{{item.username}}/.ssh/authorized_keys
    owner: "{{ item.username }}"
    group: adm
    mode: 0600
  with_items: "{{ admin_users }}"
