# Make infra user and remove default creds from cumulus
  - name: Create a login user
    user:
      name: "{{ mgmt_user }}"
      groups:
        - sudo
        - netedit
      state: present
      shell: /bin/bash

  - name: Install public ssh key
    authorized_key:
      user: "{{ mgmt_user }}"
      state: present
      key: "http://{{ cl_oob_server }}/authorized_keys"

  - name: Set passwordless sudo for mgmt user
    copy:
      content: "{{ mgmt_user }} ALL=(ALL) NOPASSWD:ALL"
      dest: /etc/sudoers.d/10_{{ mgmt_user }}

#  - name: Set nologin for cumulus user
#    user:
#      name: cumulus
#      shell: /usr/sbin/nologin
